sudo: false
dist: precise

language: python
python:
  - "2.6"
  - "2.7"

install:
    - travis_retry pip install tox-travis
    - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then travis_retry pip install flake8; fi
    - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then travis_retry nvm install; fi
    - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then travis_retry npm install; fi

script:
    - tox
    - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then ./node_modules/.bin/grunt --verbose; fi
    - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then flake8 kickoff/ --exclude=kickoff/test/ --max-line-length=2000 --ignore=E402,E711; fi

after_success:
    - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then travis_retry pip install coveralls && coveralls; fi
